"""The speaker-embedding boundary and the enrollment quality gates.

Two properties dominate:

* **Production can never reach the fake provider.** A stand-in template would be
  encrypted, stored and marked eligible while identifying nobody -- a silent wrong
  answer, which is worse than a loud missing dependency.
* **A gate that cannot be measured says so.** `NOT_MEASURED` is a real verdict, not
  a synonym for PASS.

No microphone and no model are involved: audio is generated by the Phase 2
deterministic sources.
"""

from __future__ import annotations

import math

import pytest

from mom_igd.audio.backend import CaptureProfile, SampleFormat
from mom_igd.audio.fake_backend import ClippingSource, SilenceSource, SineSource
from mom_igd.enrollment.fake_provider import (
    FAKE_MODEL_NAME,
    FAKE_MODEL_SHA256,
    BrokenFakeProvider,
    DriftingFakeProvider,
    FakeSpeakerEmbeddingProvider,
    fake_model_spec,
)
from mom_igd.enrollment.provider import (
    EMBEDDING_TOLERANCE,
    EmbeddingValidationError,
    ModelUnavailableError,
    ProviderError,
    SpeakerEmbeddingProvider,
    SpeakerModelSpec,
    cosine_similarity,
    validate_embedding,
    verify_artifact_sha256,
)
from mom_igd.enrollment.quality import (
    MIN_INTRA_SPEAKER_COSINE,
    EnrollmentQualityThresholds,
    GateStatus,
    estimate_snr_db,
    estimate_speech_active_ratio,
    evaluate_enrollment,
    evaluate_sample,
    pairwise_cosines,
)

SR = 48_000
PROFILE = CaptureProfile(
    sample_rate=SR, channels=1, sample_format=SampleFormat.INT16, chunk_seconds=30
)


def _pcm(source, seconds: float) -> bytes:
    return source.read(0, int(SR * seconds), PROFILE)


def _sample(**kwargs):
    base = dict(
        index=0, channels=1, sample_rate_hz=SR, dropped_frames=0, xrun_callbacks=0
    )
    base.update(kwargs)
    return evaluate_sample(**base)


def _good_samples(count: int = 5):
    return [
        _sample(index=i, pcm=_pcm(SineSource(level_dbfs=-20.0), 10)) for i in range(count)
    ]


def _report(**kwargs):
    provider = FakeSpeakerEmbeddingProvider()
    same = [provider.embed(b"one-voice", sample_rate_hz=SR, channels=1) for _ in range(5)]
    base = dict(
        samples=_good_samples(),
        embeddings=same,
        device_fingerprint="f" * 32,
        selected_fingerprint="f" * 32,
        device_transport="USB",
        calibration_age_days=1.0,
        calibration_verdict="GOOD",
    )
    base.update(kwargs)
    return evaluate_enrollment(**base)


def _keys(report, status: GateStatus) -> list[str]:
    everything = list(report.gates) + [g for s in report.samples for g in s.gates]
    return [g.key for g in everything if g.status is status]


# ================================================== production cannot use fake


def test_production_provider_loading_fails_closed(config) -> None:
    """The registry declares no model, so enrollment must stop -- not substitute."""
    from mom_igd.enrollment.provider import load_provider_from_registry

    with pytest.raises(ModelUnavailableError) as excinfo:
        load_provider_from_registry(config, None)
    message = str(excinfo.value)
    assert "registry" in message.lower()
    # The message must explain, not merely fail.
    assert "phase-3-speaker-model-selection" in message


def test_the_production_loader_never_returns_a_test_double(config) -> None:
    """Guard against a future 'temporary' fallback being added here."""
    import inspect

    from mom_igd.enrollment import provider as provider_module

    source = inspect.getsource(provider_module)
    assert "fake_provider" not in source, (
        "provider.py must not import or reference the fake provider; production "
        "would then be one edit away from storing a stand-in template"
    )
    assert "FakeSpeakerEmbeddingProvider" not in source


def test_the_fake_provider_is_labelled_as_a_test_double() -> None:
    provider = FakeSpeakerEmbeddingProvider()
    assert provider.is_test_double is True
    assert FAKE_MODEL_NAME.startswith("FAKE-")
    assert provider.spec.name.startswith("FAKE-")
    # An all-f hash cannot collide with a real artefact.
    assert FAKE_MODEL_SHA256 == "f" * 64
    assert "NOT A MODEL" in provider.spec.license


def test_the_fake_provider_satisfies_the_protocol() -> None:
    assert isinstance(FakeSpeakerEmbeddingProvider(), SpeakerEmbeddingProvider)


# ============================================================== provider spec


@pytest.mark.parametrize(
    "override",
    [
        {"name": ""},
        {"version": " "},
        {"sha256": "abc"},
        {"sha256": "F" * 64},
        {"embedding_dim": 4},
        {"embedding_dim": 99_999},
        {"sample_rate_hz": 0},
        {"channels": 3},
        {"preprocessing_id": ""},
    ],
)
def test_a_model_spec_without_verifiable_provenance_is_refused(override) -> None:
    base = dict(
        name="m",
        version="1",
        sha256="c" * 64,
        embedding_dim=192,
        sample_rate_hz=16_000,
        channels=1,
        preprocessing_id="p1",
        license="L",
        source="S",
    )
    base.update(override)
    with pytest.raises(ProviderError):
        SpeakerModelSpec(**base)


def test_artifact_hash_is_verified_before_loading(tmp_path) -> None:
    """A model artefact is executable input; a mismatch must refuse, not warn."""
    import hashlib

    artefact = tmp_path / "model.onnx"
    artefact.write_bytes(b"pretend model bytes")
    real = hashlib.sha256(b"pretend model bytes").hexdigest()

    assert verify_artifact_sha256(artefact, real) == real
    with pytest.raises(ProviderError, match="Refusing to load"):
        verify_artifact_sha256(artefact, "d" * 64)


def test_a_missing_artifact_is_model_unavailable(tmp_path) -> None:
    with pytest.raises(ModelUnavailableError, match="never downloads"):
        verify_artifact_sha256(tmp_path / "absent.onnx", "d" * 64)


# =========================================================== embedding output


def test_the_fake_provider_is_deterministic() -> None:
    provider = FakeSpeakerEmbeddingProvider()
    first = provider.embed(b"audio-bytes" * 50, sample_rate_hz=SR, channels=1)
    second = provider.embed(b"audio-bytes" * 50, sample_rate_hz=SR, channels=1)
    assert first == second
    assert cosine_similarity(first, second) == pytest.approx(1.0)


def test_different_audio_gives_a_different_embedding() -> None:
    provider = FakeSpeakerEmbeddingProvider()
    a = provider.embed(b"voice-a" * 50, sample_rate_hz=SR, channels=1)
    b = provider.embed(b"voice-b" * 50, sample_rate_hz=SR, channels=1)
    assert a != b


def test_a_valid_embedding_is_unit_length() -> None:
    vector = FakeSpeakerEmbeddingProvider().embed(
        b"x" * 1000, sample_rate_hz=SR, channels=1
    )
    assert math.sqrt(sum(v * v for v in vector)) == pytest.approx(1.0, abs=EMBEDDING_TOLERANCE)


@pytest.mark.parametrize(
    ("mode", "expected"),
    [
        ("wrong_dim", "dimensions"),
        ("nan", "non-finite"),
        ("inf", "non-finite"),
        ("zero", "zero vector"),
        ("unnormalised", "L2 norm"),
    ],
)
def test_an_invalid_vector_is_rejected_at_the_consumer(mode: str, expected: str) -> None:
    """The consumer validates: a third-party provider cannot be trusted to self-police."""
    raw = BrokenFakeProvider(mode=mode).embed(b"x", sample_rate_hz=SR, channels=1)
    with pytest.raises(EmbeddingValidationError, match=expected):
        validate_embedding(raw, spec=fake_model_spec())


def test_a_format_mismatch_is_refused() -> None:
    """A rate or channel mismatch changes the embedding for non-speaker reasons."""
    provider = FakeSpeakerEmbeddingProvider()
    with pytest.raises(ValueError, match="expects 48000 Hz"):
        provider.embed(b"x", sample_rate_hz=16_000, channels=1)
    with pytest.raises(ValueError, match="channel"):
        provider.embed(b"x", sample_rate_hz=SR, channels=2)


def test_close_releases_the_provider_and_is_idempotent() -> None:
    provider = FakeSpeakerEmbeddingProvider()
    provider.close()
    provider.close()
    assert provider.closed is True
    with pytest.raises(RuntimeError, match="closed"):
        provider.embed(b"x", sample_rate_hz=SR, channels=1)


def test_the_context_manager_closes_the_provider() -> None:
    """ADR-0004 forbids a resident model; the contract makes release automatic."""
    with FakeSpeakerEmbeddingProvider() as provider:
        provider.embed(b"x", sample_rate_hz=SR, channels=1)
        assert provider.closed is False
    assert provider.closed is True


def test_cosine_similarity_rejects_mismatched_lengths() -> None:
    with pytest.raises(EmbeddingValidationError, match="different lengths"):
        cosine_similarity([1.0, 0.0], [1.0, 0.0, 0.0])


def test_pairwise_cosines_covers_every_unordered_pair() -> None:
    provider = FakeSpeakerEmbeddingProvider()
    vectors = [provider.embed(f"v{i}".encode(), sample_rate_hz=SR, channels=1) for i in range(4)]
    assert len(pairwise_cosines(vectors)) == 6  # 4 choose 2
    assert pairwise_cosines(vectors[:1]) == []


# ============================================================ sample quality


def test_a_healthy_sample_passes() -> None:
    sample = _sample(pcm=_pcm(SineSource(level_dbfs=-20.0), 10))
    assert sample.status is GateStatus.PASS
    assert sample.accepted is True
    assert sample.seconds == pytest.approx(10.0, abs=0.01)
    assert sample.speech_active_ratio == pytest.approx(1.0)


@pytest.mark.parametrize(
    ("label", "kwargs", "gate"),
    [
        ("too short", {"pcm": _pcm(SineSource(level_dbfs=-20.0), 2)}, "duration"),
        ("silence", {"pcm": _pcm(SilenceSource(), 10)}, "not_silent"),
        ("clipping", {"pcm": _pcm(ClippingSource(overdrive_db=6.0), 10)}, "no_clipping"),
        ("too quiet", {"pcm": _pcm(SineSource(level_dbfs=-55.0), 10)}, "level_not_too_low"),
        (
            "dropped frames",
            {"pcm": _pcm(SineSource(level_dbfs=-20.0), 10), "dropped_frames": 12},
            "no_dropped_frames",
        ),
        (
            "xrun",
            {"pcm": _pcm(SineSource(level_dbfs=-20.0), 10), "xrun_callbacks": 1},
            "no_xruns",
        ),
    ],
)
def test_each_defect_rejects_the_sample_by_its_own_gate(label, kwargs, gate) -> None:
    sample = _sample(**kwargs)
    assert sample.status is GateStatus.REJECT, label
    assert sample.accepted is False
    rejected = [g.key for g in sample.gates if g.status is GateStatus.REJECT]
    assert gate in rejected, f"{label}: expected {gate}, got {rejected}"


def test_a_dropped_frame_is_never_tolerated() -> None:
    """A gap in an enrollment sample is a hole in biometric evidence."""
    assert EnrollmentQualityThresholds().max_dropped_frames == 0
    assert EnrollmentQualityThresholds().max_xrun_callbacks == 0


def test_every_gate_carries_actionable_advice() -> None:
    """A verdict an operator cannot act on wastes the operator's time."""
    for sample in (_sample(pcm=_pcm(SilenceSource(), 10)), _sample(pcm=_pcm(SineSource(level_dbfs=-20.0), 2))):
        for gate in sample.gates:
            if gate.status is GateStatus.REJECT:
                assert len(gate.detail) > 25, f"{gate.key} advice is too thin"


# ================================================ speech ratio and SNR honesty


def test_a_steady_signal_reports_snr_as_unmeasurable_not_zero() -> None:
    """The Phase 2 noise floor is a low percentile of block RMS.

    For a constant-level signal it equals the signal, so the SNR estimate is
    meaningless. Reporting 0 dB would flunk a healthy sample -- which is exactly the
    bug this test exists to prevent.
    """
    sample = _sample(pcm=_pcm(SineSource(level_dbfs=-20.0), 10))
    assert sample.estimated_snr_db is None
    snr_gate = next(g for g in sample.gates if g.key == "estimated_snr")
    assert snr_gate.status is GateStatus.NOT_MEASURED
    assert "unmeasurable" in snr_gate.detail
    # And it does not drag the sample down.
    assert sample.status is GateStatus.PASS


def test_estimate_snr_returns_none_when_the_floor_meets_the_signal() -> None:
    assert estimate_snr_db(-20.0, -20.0) is None
    assert estimate_snr_db(-20.0, -20.5) is None
    assert estimate_snr_db(-20.0, -45.0) == pytest.approx(25.0)


def test_the_speech_ratio_is_energy_relative_not_floor_relative() -> None:
    """A steady sample is 100 % active; silence is 0 %."""
    steady = estimate_speech_active_ratio(
        _pcm(SineSource(level_dbfs=-20.0), 5), channels=1, sample_rate_hz=SR
    )
    quiet = estimate_speech_active_ratio(
        _pcm(SilenceSource(), 5), channels=1, sample_rate_hz=SR
    )
    assert steady == pytest.approx(1.0)
    assert quiet == pytest.approx(0.0) or quiet == 1.0


def test_the_speech_ratio_handles_audio_shorter_than_one_window() -> None:
    assert estimate_speech_active_ratio(b"\x00\x00", channels=1, sample_rate_hz=SR) == 0.0


# ======================================================== enrollment verdict


def test_a_good_usb_enrollment_passes() -> None:
    report = _report()
    assert report.status is GateStatus.PASS
    assert report.accepted is True
    assert report.total_speech_seconds >= 30.0
    assert report.min_pair_cosine == pytest.approx(1.0)


def test_an_internal_microphone_warns_but_is_accepted() -> None:
    """Development enrollment is legitimate; it just is not production eligible."""
    report = _report(device_transport="INTERNAL")
    assert report.status is GateStatus.WARN
    assert report.accepted is True
    gate = next(g for g in report.gates if g.key == "production_device")
    assert gate.status is GateStatus.WARN
    assert "DEVELOPMENT_ONLY" in gate.detail


def test_inconsistent_samples_are_rejected_by_the_cosine_floor() -> None:
    drifting = DriftingFakeProvider()
    vectors = [drifting.embed(b"x", sample_rate_hz=SR, channels=1) for _ in range(5)]
    report = _report(embeddings=vectors)
    assert report.status is GateStatus.REJECT
    assert "intra_speaker_consistency" in _keys(report, GateStatus.REJECT)
    assert report.min_pair_cosine < MIN_INTRA_SPEAKER_COSINE


def test_the_cosine_floor_is_the_architecture_value() -> None:
    assert MIN_INTRA_SPEAKER_COSINE == 0.80
    assert EnrollmentQualityThresholds().min_intra_speaker_cosine == 0.80


def test_a_single_embedding_leaves_consistency_not_measured() -> None:
    provider = FakeSpeakerEmbeddingProvider()
    report = _report(embeddings=[provider.embed(b"x", sample_rate_hz=SR, channels=1)])
    gate = next(g for g in report.gates if g.key == "intra_speaker_consistency")
    assert gate.status is GateStatus.NOT_MEASURED
    assert report.min_pair_cosine is None


def test_missing_calibration_evidence_rejects_the_enrollment() -> None:
    report = _report(calibration_age_days=None, calibration_verdict=None)
    assert "calibration_freshness" in _keys(report, GateStatus.REJECT)


def test_stale_calibration_rejects_the_enrollment() -> None:
    report = _report(calibration_age_days=40.0)
    assert "calibration_freshness" in _keys(report, GateStatus.REJECT)


def test_a_bad_calibration_verdict_rejects_the_enrollment() -> None:
    report = _report(calibration_verdict="TOO_QUIET")
    assert "calibration_verdict" in _keys(report, GateStatus.REJECT)


def test_a_device_change_mid_enrollment_rejects_it() -> None:
    """A template must be tied to the microphone it was captured on."""
    report = _report(device_fingerprint="a" * 32, selected_fingerprint="f" * 32)
    assert "device_consistency" in _keys(report, GateStatus.REJECT)


def test_a_missing_device_fingerprint_rejects_the_enrollment() -> None:
    report = _report(device_fingerprint=None, selected_fingerprint=None)
    assert "device_consistency" in _keys(report, GateStatus.REJECT)


def test_insufficient_total_speech_rejects_the_enrollment() -> None:
    report = _report(samples=_good_samples(2))
    assert "total_speech_duration" in _keys(report, GateStatus.REJECT)


def test_the_report_serialises_without_audio_or_vectors() -> None:
    payload = _report().to_dict()
    blob = repr(payload).lower()
    for forbidden in ("centroid", "embedding\":", "pcm", "ciphertext"):
        assert forbidden not in blob
    assert payload["status"] == "PASS"
    assert len(payload["samples"]) == 5


def test_thresholds_declare_which_values_are_provisional() -> None:
    """An invented threshold presented as calibrated stops anyone re-examining it."""
    payload = EnrollmentQualityThresholds().to_dict()
    assert "min_snr_db" in payload["provisional"]
    assert "min_intra_speaker_cosine" not in payload["provisional"]
    assert "NOT been calibrated" in payload["provisional_note"]
